# backend/pipeline.py
from typing import TypedDict, List, Dict, Any
import re

from langgraph.graph import StateGraph, END
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate

from backend.rag.retriever import get_retriever
from backend.agents.diagnostic import diagnose_understanding
from backend.agents.tutor import build_reexplain_chain
from backend.agents.critique import critique_explanation
from backend.agents.quiz import generate_quiz
from backend.config import GROQ_API_KEY, GROQ_MODEL


# =========================
# Tutor State
# =========================

class TutorState(TypedDict):
    question: str
    student_answer: str
    context_chunks: List[str]
    diagnosis: str
    verdict: str
    retry_count: int
    quiz_failed: bool


# =========================
# Helpers
# =========================

def _llm_verdict_is_correct(raw_text: str) -> bool:
    """
    Interpret LLM output as CORRECT / INCORRECT safely.

    Rules:
    - If 'INCORRECT' appears anywhere → INCORRECT.
    - Else if 'CORRECT' appears → CORRECT.
    - Else → INCORRECT (safe default).
    """
    up = raw_text.upper()
    if "INCORRECT" in up:
        return False
    if "CORRECT" in up:
        return True
    return False


def grade_descriptive(
    context: str,
    question: str,
    reference_answer: str,
    student_answer: str,
) -> bool:
    """
    Strict grading for descriptive questions.
    Returns True if CORRECT, else False.
    """
    llm = ChatGroq(
        api_key=GROQ_API_KEY,
        model=GROQ_MODEL,
        temperature=0.0,
    )

    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                "You are a VERY strict examiner.\n"
                "- Use ONLY the given context and reference answer.\n"
                "- Respond ONLY with CORRECT or INCORRECT.\n"
                "- If the student answer is vague, generic, or misses key ideas, "
                "respond with INCORRECT."
            ),
            (
                "human",
                """
Context:
{context}

Question:
{question}

Reference ideal answer:
{reference_answer}

Student answer:
{student_answer}

Remember: Reply ONLY with CORRECT or INCORRECT.
""",
            ),
        ]
    )

    response = (prompt | llm).invoke(
        {
            "context": context,
            "question": question,
            "reference_answer": reference_answer,
            "student_answer": student_answer,
        }
    )

    return _llm_verdict_is_correct(response.content)


def parse_quiz(quiz_text: str) -> Dict[str, Any]:
    """
    Parse the quiz text generated by generate_quiz into structured MCQs and
    descriptive questions.

    Expected format:

    MCQ 1:
    Question: ...
    A) ...
    B) ...
    C) ...
    D) ...
    Answer: <A/B/C/D>

    DESCRIPTIVE 1:
    Question: ...
    Answer: ...
    """

    mcq_pattern = re.compile(
        r"MCQ\s+(\d+):\s*"
        r"[\r\n]+Question:\s*(.+?)\r?\n"
        r"A\)\s*(.+?)\r?\n"
        r"B\)\s*(.+?)\r?\n"
        r"C\)\s*(.+?)\r?\n"
        r"D\)\s*(.+?)\r?\n"
        r"Answer:\s*([A-D])",
        re.IGNORECASE,
    )

    desc_pattern = re.compile(
        r"DESCRIPTIVE\s+(\d+):\s*"
        r"[\r\n]+Question:\s*(.+?)\r?\n"
        r"Answer:\s*(.+?)(?=\r?\n\r?\n|$)",
        re.IGNORECASE | re.DOTALL,
    )

    mcqs = []
    for match in mcq_pattern.finditer(quiz_text):
        idx = int(match.group(1))
        question = match.group(2).strip()
        options = {
            "A": match.group(3).strip(),
            "B": match.group(4).strip(),
            "C": match.group(5).strip(),
            "D": match.group(6).strip(),
        }
        answer = match.group(7).strip().upper()
        mcqs.append(
            {
                "index": idx,
                "question": question,
                "options": options,
                "answer": answer,
            }
        )

    descs = []
    for match in desc_pattern.finditer(quiz_text):
        idx = int(match.group(1))
        question = match.group(2).strip()
        answer = match.group(3).strip()
        descs.append(
            {
                "index": idx,
                "question": question,
                "answer": answer,
            }
        )

    return {
        "mcqs": mcqs,
        "descriptive": descs,
    }


# =========================
# Nodes
# =========================

def retrieve_context_node(state: TutorState) -> TutorState:
    retriever = get_retriever(k=3)
    docs = retriever.invoke(state["question"])

    state["context_chunks"] = [d.page_content for d in docs]
    state["retry_count"] = 0
    state["quiz_failed"] = False

    return state


def ask_question_node(state: TutorState) -> TutorState:
    print("\n📘 Tutor Question:")
    print(state["question"])

    state["student_answer"] = input("\nYour answer:\n> ")
    return state


def diagnose_node(state: TutorState) -> TutorState:
    result = diagnose_understanding(
        question=state["question"],
        student_answer=state["student_answer"],
        context_chunks=state["context_chunks"],
    )

    state["verdict"] = result["verdict"]
    state["diagnosis"] = result["analysis"]

    print(f"\n🧠 Diagnostic Verdict: {state['verdict']}")
    return state


def reexplain_node(state: TutorState) -> TutorState:
    print("\n🔁 Re-explaining the concept:\n")

    chain = build_reexplain_chain()
    response = chain.invoke(
        {
            "context": "\n\n".join(state["context_chunks"]),
            "question": state["question"],
            "diagnosis": state["diagnosis"],
        }
    )

    # Always show explanation
    print(response.content)

    # Critique after explanation
    is_good = critique_explanation(
        context="\n\n".join(state["context_chunks"]),
        explanation=response.content,
    )

    state["retry_count"] += 1

    if not is_good and state["retry_count"] < 2:
        print("\n⚠️ Explanation could be improved. Trying again...\n")
        return state

    print("\n✅ Explanation accepted.\n")
    return state


def quiz_node(state: TutorState) -> TutorState:
    print("\n📝 Quiz Time!\n")

    quiz = generate_quiz(state["question"])
    quiz_text = quiz["quiz"]

    # Show quiz to the student
    print(quiz_text)

    # Parse quiz into structure
    parsed = parse_quiz(quiz_text)
    mcqs = parsed["mcqs"]
    descs = parsed["descriptive"]

    # Safety: if model didn't follow format, fail safely
    if len(mcqs) != 3 or len(descs) != 2:
        print("\n⚠️ Quiz format unexpected. Skipping grading; marking as failed for safety.\n")
        state["quiz_failed"] = True
        return state

    context = "\n\n".join(state["context_chunks"])

    # ---- MCQ Answers ----
    mcq_correct = 0
    for i, mcq in enumerate(mcqs, start=1):
        # Show the MCQ nicely (optional but helpful)
        print(f"\nMCQ {i}: {mcq['question']}")
        for opt_label, opt_text in mcq["options"].items():
            print(f"{opt_label}) {opt_text}")

        while True:
            ans = input(f"\nYour answer for MCQ {i} (A/B/C/D): ").strip().upper()
            if ans in {"A", "B", "C", "D"}:
                break
            print("Invalid option. Please enter A, B, C, or D only.")

        if ans == mcq["answer"]:
            mcq_correct += 1

    # ---- Descriptive Answers ----
    desc_correct = 0
    for i, desc in enumerate(descs, start=1):
        print(f"\nDESCRIPTIVE {i}: {desc['question']}")
        ans = input("Your answer:\n> ")
        is_correct = grade_descriptive(
            context=context,
            question=desc["question"],
            reference_answer=desc["answer"],
            student_answer=ans,
        )
        if is_correct:
            desc_correct += 1

    # Pass criteria: at least 2/3 MCQs + 1/2 descriptive
    state["quiz_failed"] = not (mcq_correct >= 2 and desc_correct >= 1)

    if state["quiz_failed"]:
        print(
            f"\n❌ Quiz failed "
            f"({mcq_correct}/3 MCQs correct, {desc_correct}/2 descriptive correct).\n"
        )
    else:
        print(
            f"\n✅ Quiz passed "
            f"({mcq_correct}/3 MCQs correct, {desc_correct}/2 descriptive correct).\n"
        )

    return state


# =========================
# Routing Logic
# =========================

def route_after_diagnosis(state: TutorState):
    # If concept understood → go to quiz, else re-explain.
    return "quiz" if state["verdict"] == "UNDERSTOOD" else "reexplain"


def route_after_quiz(state: TutorState):
    # If quiz failed → re-explain, else finish.
    return "reexplain" if state["quiz_failed"] else END


# =========================
# Graph Definition
# =========================

graph = StateGraph(TutorState)

graph.add_node("retrieve_context", retrieve_context_node)
graph.add_node("ask_question", ask_question_node)
graph.add_node("diagnose", diagnose_node)
graph.add_node("reexplain", reexplain_node)
graph.add_node("quiz", quiz_node)

graph.set_entry_point("retrieve_context")

graph.add_edge("retrieve_context", "ask_question")
graph.add_edge("ask_question", "diagnose")

graph.add_conditional_edges(
    "diagnose",
    route_after_diagnosis,
    {"reexplain": "reexplain", "quiz": "quiz"},
)

graph.add_conditional_edges(
    "quiz",
    route_after_quiz,
    {"reexplain": "reexplain", END: END},
)

graph.add_edge("reexplain", "ask_question")

tutor_graph = graph.compile()
